perturbed_somatic_mut:
  gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p001_caseFreq-0p0099_nFeatures-100.csv
  gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p01_caseFreq-0p0917_nFeatures-100.csv
  gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p05_caseFreq-0p3448_nFeatures-100.csv
  gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p1_caseFreq-0p5263_nFeatures-100.csv
  gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p2_caseFreq-0p7143_nFeatures-100.csv
  gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-10.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-10.csv
  gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-100.csv
    target_file: y_gene-AR_OR-10_ctrlFreq-0p5_caseFreq-0p9091_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p001_caseFreq-0p001_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p01_caseFreq-0p01_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p05_caseFreq-0p05_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p1_caseFreq-0p1_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p2_caseFreq-0p2_nFeatures-100.csv
  gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-10.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-10.csv
  gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-100.csv
    target_file: y_gene-AR_OR-1_ctrlFreq-0p5_caseFreq-0p5_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p001_caseFreq-0p0011_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p01_caseFreq-0p011_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p05_caseFreq-0p0547_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p1_caseFreq-0p1089_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p2_caseFreq-0p2157_nFeatures-100.csv
  gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-10.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-10.csv
  gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-100.csv
    target_file: y_gene-AR_OR-1p1_ctrlFreq-0p5_caseFreq-0p5238_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p001_caseFreq-0p002_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p01_caseFreq-0p0198_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p05_caseFreq-0p0952_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p1_caseFreq-0p1818_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p2_caseFreq-0p3333_nFeatures-100.csv
  gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-10.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-10.csv
  gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-100.csv
    target_file: y_gene-AR_OR-2_ctrlFreq-0p5_caseFreq-0p6667_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p001_caseFreq-0p0292_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p01_caseFreq-0p2326_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p05_caseFreq-0p6122_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p1_caseFreq-0p7692_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p2_caseFreq-0p8824_nFeatures-100.csv
  gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-10:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-10.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-10.csv
  gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-100:
    data_file: somatic_mut_gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-100.csv
    target_file: y_gene-AR_OR-30_ctrlFreq-0p5_caseFreq-0p9677_nFeatures-100.csv
